services:
  backend:
    container_name: r-backend
    build:
      context: .
      dockerfile: ./_docker/laravel/Dockerfile
    volumes:
      - ./:/var/www/restaurant_api
      - ./_docker/laravel/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      db:
        condition: service_healthy
    networks:
      - default_network

  nginx:
    container_name: r-nginx
    image: nginx:latest
    restart: always
    volumes:
        - ./_docker/nginx/:/etc/nginx/conf.d/
    ports:
      - "8000:80"
    depends_on:
      - backend
    networks:
      - default_network

  db:
    container_name: r-db
    image: postgres:latest
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - default_network

networks:
  default_network:
    driver: bridge

volumes:
  file-storage:
  db-data:
